usr/bin/mongo
usr/bin/mongodump
usr/bin/mongoexport
usr/bin/mongofiles
usr/bin/mongoimport
usr/bin/mongorestore
usr/bin/mongostat
usr/share/lintian/overrides/mongodb-clients
usr/share/man/man1/mongo.1.gz
usr/share/man/man1/mongodump.1.gz
usr/share/man/man1/mongoexport.1.gz
usr/share/man/man1/mongofiles.1.gz
usr/share/man/man1/mongoimport.1.gz
usr/share/man/man1/mongoimportjson.1.gz
usr/share/man/man1/mongorestore.1.gz
usr/share/man/man1/mongosniff.1.gz
usr/share/man/man1/mongostat.15.gz

